# Generated by Django 3.0.5 on 2020-04-13 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coursemodel',
            name='teachers',
            field=models.ManyToManyField(null=True, to='login.TeacherInformationModel'),
        ),
        migrations.AlterField(
            model_name='majormodel',
            name='courses',
            field=models.ManyToManyField(null=True, to='login.CourseModel'),
        ),
    ]
