# Generated by Django 3.0.5 on 2020-04-15 08:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='classmodel',
            name='students',
        ),
        migrations.CreateModel(
            name='CourseScoreModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.CharField(max_length=16, verbose_name='课程得分')),
                ('course_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='login.CourseModel')),
                ('student_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='login.StudentInformationModel')),
            ],
        ),
    ]
