# Generated by Django 3.0.4 on 2020-04-04 16:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='email',
        ),
        migrations.AlterField(
            model_name='user',
            name='name',
            field=models.CharField(max_length=128, unique=True, verbose_name='学生ID'),
        ),
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(max_length=256, verbose_name='密码'),
        ),
        migrations.CreateModel(
            name='StudentInformationModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='邮箱')),
                ('name', models.CharField(max_length=30, null=True, verbose_name='姓名')),
                ('sex', models.CharField(max_length=20, null=True, verbose_name='性别')),
                ('idc', models.CharField(max_length=20, null=True, verbose_name='身份证')),
                ('age', models.CharField(max_length=20, null=True, verbose_name='年龄')),
                ('major', models.CharField(max_length=30, null=True, verbose_name='专业')),
                ('stu_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='login.User', to_field='name')),
            ],
            options={
                'verbose_name': '用户信息',
                'verbose_name_plural': '用户信息',
                'ordering': ['stu_id'],
            },
        ),
        migrations.CreateModel(
            name='StudentAwardsRecodeModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('award_type', models.CharField(max_length=5, null=True, verbose_name='奖惩记录类别')),
                ('award_content', models.CharField(max_length=50, null=True, verbose_name='奖惩信息')),
                ('award_date', models.DateTimeField(null=True, verbose_name='奖惩日期')),
                ('stu_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='login.User', to_field='name')),
            ],
            options={
                'verbose_name': '奖惩信息',
                'verbose_name_plural': '奖惩信息',
                'ordering': ['stu_id'],
            },
        ),
    ]
