# Generated by Django 3.0.5 on 2020-04-13 20:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0002_auto_20200413_2014'),
    ]

    operations = [
        migrations.AddField(
            model_name='coursemodel',
            name='students',
            field=models.ManyToManyField(blank=True, null=True, to='login.StudentInformationModel'),
        ),
        migrations.AddField(
            model_name='studentinformationmodel',
            name='class_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='login.ClassModel'),
        ),
        migrations.AlterField(
            model_name='coursemodel',
            name='teachers',
            field=models.ManyToManyField(blank=True, null=True, to='login.TeacherInformationModel'),
        ),
        migrations.AlterField(
            model_name='majormodel',
            name='courses',
            field=models.ManyToManyField(blank=True, null=True, to='login.CourseModel'),
        ),
    ]
