# Generated by Django 3.0.4 on 2020-04-04 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0002_auto_20200404_1612'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='sex',
        ),
        migrations.AlterField(
            model_name='studentinformationmodel',
            name='major',
            field=models.CharField(choices=[('080901', '计算机科学与技术'), ('080902', '软件工程'), ('080903', '网络工程'), ('080904K', '信息安全')], default='计算机科学与技术', max_length=30),
        ),
        migrations.AlterField(
            model_name='studentinformationmodel',
            name='sex',
            field=models.CharField(choices=[('male', '男'), ('female', '女')], default='男', max_length=32),
        ),
    ]
