# Generated by Django 3.0.5 on 2020-04-16 10:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0003_classmodel_students'),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseClassModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('maxNum', models.CharField(max_length=16, verbose_name='最大人数')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='login.TeacherInformationModel')),
            ],
            options={
                'verbose_name': '课程班级',
                'verbose_name_plural': '课程班级',
                'ordering': ['maxNum'],
            },
        ),
        migrations.CreateModel(
            name='StudentScoreModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.CharField(max_length=16, null=True, verbose_name='分数')),
                ('state', models.CharField(max_length=16, null=True, verbose_name='状态')),
            ],
            options={
                'verbose_name': '成绩',
                'verbose_name_plural': '成绩',
                'ordering': ['score'],
            },
        ),
        migrations.RemoveField(
            model_name='coursemodel',
            name='students',
        ),
        migrations.RemoveField(
            model_name='coursemodel',
            name='teachers',
        ),
        migrations.RemoveField(
            model_name='studentinformationmodel',
            name='class_id',
        ),
        migrations.DeleteModel(
            name='CourseScoreModel',
        ),
        migrations.AddField(
            model_name='studentscoremodel',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='login.StudentInformationModel'),
        ),
        migrations.AddField(
            model_name='coursemodel',
            name='courseClass',
            field=models.ManyToManyField(blank=True, null=True, to='login.CourseClassModel'),
        ),
        migrations.AddField(
            model_name='coursemodel',
            name='studentsScore',
            field=models.ManyToManyField(blank=True, null=True, to='login.StudentScoreModel'),
        ),
    ]
