# Generated by Django 3.0.5 on 2020-04-13 22:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0003_auto_20200413_2059'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coursestudentmodel',
            name='course_id',
        ),
        migrations.RemoveField(
            model_name='coursestudentmodel',
            name='student_id',
        ),
        migrations.DeleteModel(
            name='ClassStudentModel',
        ),
        migrations.DeleteModel(
            name='CourseStudentModel',
        ),
    ]
