# Generated by Django 3.0.5 on 2020-04-12 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0004_auto_20200410_0256'),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseModel',
            fields=[
                ('course_id', models.AutoField(primary_key=True, serialize=False, verbose_name='课程ID')),
                ('course_name', models.CharField(max_length=64, verbose_name='课程名称')),
                ('create_date', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': '课程',
                'verbose_name_plural': '课程',
                'ordering': ['create_date'],
            },
        ),
    ]
