# Generated by Django 3.0.4 on 2020-04-12 00:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0004_auto_20200410_0256'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentawardsrecodemodel',
            name='award_date',
            field=models.DateField(null=True, verbose_name='奖惩日期'),
        ),
    ]
