# Generated by Django 3.0.5 on 2020-04-16 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0004_auto_20200416_1046'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coursemodel',
            name='studentsScore',
        ),
        migrations.AddField(
            model_name='courseclassmodel',
            name='studentsScore',
            field=models.ManyToManyField(blank=True, null=True, to='login.StudentScoreModel'),
        ),
    ]
