# Generated by Django 3.0.5 on 2020-04-19 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0007_auto_20200417_0920'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='courseclassmodel',
            options={'ordering': ['teacher'], 'verbose_name': '课程班级', 'verbose_name_plural': '课程班级'},
        ),
        migrations.AlterModelOptions(
            name='studentscoremodel',
            options={'ordering': ['courseClass'], 'verbose_name': '成绩', 'verbose_name_plural': '成绩'},
        ),
        migrations.RenameField(
            model_name='studentscoremodel',
            old_name='state',
            new_name='states',
        ),
        migrations.AlterField(
            model_name='studentinformationmodel',
            name='major',
            field=models.CharField(choices=[('080901', '计算机科学与技术'), ('080902', '软件工程'), ('080903', '网络工程'), ('080904', '信息安全'), ('000001', '纺织化学工程系'), ('000002', '应用化学系'), ('000003', '生物工程系及基础化学部')], default='计算机科学与技术', max_length=30),
        ),
    ]
