# Generated by Django 3.0.4 on 2020-04-21 13:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0008_auto_20200419_1133'),
    ]

    operations = [
        migrations.CreateModel(
            name='Privilege',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.TextField(max_length=64)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='login.TeacherInformationModel')),
            ],
        ),
    ]
